name: Node.js Package

# on:
#   pull_request:
#     types: [closed]

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm ci
      - run: npm test
      publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
          - uses: actions/setup-node@v1
            with:
              node-version: 13
              registry-url: https://registry.npmjs.org/
          - run: npm ci
          - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.PUBLISH_NPM_TOKEN}}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
#   publish-npm:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-node@v1
#         if: github.event.pull_request.merged
#         with:
#           node-version: 13
#           registry-url: https://registry.npmjs.org/
#           ref: refs/heads/master
#       - run: git config user.name $GITHUB_ACTOR
#       - run: git config user.email gh-actions-${GITHUB_ACTOR}@github.com
#       - run: npm ci
#       - run: npm version minor --force -m "Version %s"
#       - run: git remote -v 
#       - run: git remote remove origin
#       #- run: git remote add origin git@github.com:user/repo.git  
#       - run: git remote add origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
#       - run: git add . 
#       - run: git commit -m "Push for PR."
#       - run: git push origin HEAD:master

# #- run: git push -u https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git master --tags
#       #- run: git push https://${GITHUB_ACTOR}:password@myrepository.biz/file.git --all  git push origin HEAD:master --tags
#       - run: npm publish --access public

