name: Commit date to master
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.
      
      - name: version bump
        run: |
          # do some operation that changes a file in the git repo
          git config --global user.email "59573004+crawfordsolutions@users.noreply.github.com"
          git config --global user.name "Jeff C"
          #npm version minor --force -m "Version %s" 
          npm version patch --force -m "Upgrade to %s for reasons"
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          #git config user.name "GitHub Actions Bot"
          #git config user.email "<>"
          
      - name: commit
        run: |
          # Stage the file, commit and push
          #git add package.json
          #git commit -m "bumped version"
          #git push origin master
         
